import pybullet as p
import pybullet_data
import numpy as np
import os
import time
import config
from robot import Panda
from objects import objects


# functions that the language model (LM) can use
def move_to_pose(ee_position, ee_rotz):
    panda.move_to_pose(ee_position=ee_position, ee_rotz=ee_rotz, positionGain=0.01)
    for i in range (800):
        p.stepSimulation()
        time.sleep(config.control_dt)

def close_gripper():
    panda.close_gripper()
    for i in range (300):
        p.stepSimulation()
        time.sleep(config.control_dt)

def open_gripper():
    panda.open_gripper()
    for i in range (300):
        p.stepSimulation()
        time.sleep(config.control_dt)

def task_completed():
    p.disconnect()

# create simulation and place camera
physicsClient = p.connect(p.GUI)
p.setGravity(0, 0, -9.81)
p.configureDebugVisualizer(p.COV_ENABLE_GUI, 0)
p.resetDebugVisualizerCamera(cameraDistance=config.cameraDistance, 
                                cameraYaw=config.cameraYaw,
                                cameraPitch=config.cameraPitch, 
                                cameraTargetPosition=config.cameraTargetPosition)

# load the objects
plane = objects.PyBulletObject("plane.urdf", basePosition=[0, 0, -0.625])
table = objects.PyBulletObject("table/table.urdf", basePosition=[0.5, 0, -0.625])
cube1 = objects.SimpleObject("cube.urdf", basePosition=[0.6, -0.2, 0.025], baseOrientation=p.getQuaternionFromEuler([0, 0, 0.7]))
cube2 = objects.SimpleObject("cube.urdf", basePosition=[0.6, +0.3, 0.025], baseOrientation=p.getQuaternionFromEuler([0, 0, 0.0]))

# load the robot
panda = Panda(basePosition=config.baseStartPosition,
                baseOrientation=p.getQuaternionFromEuler(config.baseStartOrientationE),
                jointStartPositions=config.jointStartPositions)


# let the scene initialize
for i in range (100):
    p.stepSimulation()
    time.sleep(config.control_dt)

# print information about relevant objects
# you will need to provide this information to the LM
# note that each side of the cube is 0.05 meters long
print(cube1.get_state())
print(cube2.get_state())

# for example, here is one response you could give to the LM:
'''
there are two blocks. Each block is a cube with sides of length 0.05

block1:
position is [0.6, -0.2, 0.025]
orientation is 0.7

block2:
position is [0.6, 0.3, 0.025]
orientation is 0
'''

# enter the code generated by the LM below: